#!/usr/bin/env node
// sandbox/srt-settings.gen.mjs - emit an @anthropic-ai/sandbox-runtime (srt) settings document on stdout,
// derived from the repo's autonomy.config.json so the OS write/egress boundary matches the gate's own
// control-plane definition. Called by sandbox/launch-sandboxed; can also be run by hand to regenerate the
// template. Pure-ish: reads ONE config file, writes ONLY stdout, no network, no deps. Fail-closed: if the
// config is missing or unparseable we still emit a SAFE-MINIMAL boundary (workspace writable, control
// plane denied, tight egress) rather than a permissive one, and warn on stderr.
//
// allowWrite = ["."]            -> the workspace (srt is launched with cwd = workspace)
// denyWrite  = control plane    -> autonomy.config.json + hooks/ + every protectedPaths entry, so a
//                                  bypassed gate inside the sandbox STILL cannot edit-away its own gates.
//                                  (srt also hard-denies .git/hooks, .claude/commands|agents, .mcp.json.)
// allowedDomains = egress allowlist (forge + registries + Anthropic API) + AUTONOMY_EXTRA_DOMAINS. This is
//                  also the ceiling on the researcher role's web-fetch. Keep it tight; broad domains like
//                  a bare github.com are an exfil/push vector (srt README), so we scope to the api/git/lfs
//                  subdomains rather than the apex where we can.
import { readFileSync } from "node:fs";

const CONFIG_PATH = process.env.AUT_CONFIG || "autonomy.config.json";
const EXTRA = (process.env.AUT_EXTRA_DOMAINS || "")
  .split(/[\s,]+/).map((s) => s.trim()).filter(Boolean);

// Default egress allowlist. Conservative: package registries + the forge's api/git/lfs hosts + the model
// API. We intentionally avoid a bare "github.com" apex (a write/push + exfil surface); api/lfs/codeload
// cover clone/fetch/push over https. Extend per-project via AUTONOMY_EXTRA_DOMAINS, never by widening here.
const DEFAULT_DOMAINS = [
  "api.anthropic.com",
  "registry.npmjs.org",
  "*.npmjs.org",
  "api.github.com",
  "codeload.github.com",
  "*.githubusercontent.com",
  "lfs.github.com",
  "pypi.org",
  "files.pythonhosted.org",
];

// The control plane that must NOT be writable from inside the sandbox. hooks/ and the config are always
// included; protectedPaths from the config are appended. These become srt denyWrite entries (deny beats
// allow for writes, so they are carved out of the writable workspace).
const ALWAYS_DENY_WRITE = [
  "autonomy.config.json",
  "hooks/",
];

function loadConfig(path) {
  try {
    const cfg = JSON.parse(readFileSync(path, "utf8"));
    return { cfg, ok: true };
  } catch (err) {
    process.stderr.write(
      `[srt-settings.gen] WARNING: could not read/parse ${path} (${err && err.message ? err.message : "error"}); `
      + "emitting SAFE-MINIMAL boundary (workspace writable, control plane denied, tight egress).\n");
    return { cfg: {}, ok: false };
  }
}

function buildSettings(cfg) {
  const protectedPaths = Array.isArray(cfg.protectedPaths) ? cfg.protectedPaths.filter(Boolean) : [];
  // Dedup denyWrite: always-deny control plane + configured protectedPaths.
  const denyWrite = Array.from(new Set([...ALWAYS_DENY_WRITE, ...protectedPaths]));
  // Allowed domains: defaults + extras, deduped, order-stable.
  const allowedDomains = Array.from(new Set([...DEFAULT_DOMAINS, ...EXTRA]));
  return {
    // A header field srt ignores but humans read; documents provenance + the self-disable invariant.
    _comment:
      "GENERATED by sandbox/srt-settings.gen.mjs from autonomy.config.json. Keep this file OUTSIDE the "
      + "workspace (outside allowWrite) so the sandboxed agent cannot edit its own boundary (the Ona "
      + "finding). allowWrite=['.'] is the workspace; denyWrite carves out the control plane; "
      + "allowedDomains is the egress + researcher web-fetch ceiling. Regenerate, do not hand-widen.",
    network: {
      allowedDomains,
      deniedDomains: [],
      allowLocalBinding: false,
    },
    filesystem: {
      // Reads: deny the home dir broadly, re-allow the workspace. Keeps SSH keys / dotfile secrets out of
      // reach while letting the agent read its own checkout. (allowRead beats denyRead for reads.)
      denyRead: ["~"],
      allowRead: ["."],
      // Writes: workspace only, with the control plane denied (deny beats allow).
      allowWrite: ["."],
      denyWrite,
    },
    // Block local IPC sockets by default (Linux seccomp / macOS allowlist). Do not add docker.sock: per the
    // srt README that is a host-escape vector.
    allowAllUnixSockets: false,
  };
}

const { cfg } = loadConfig(CONFIG_PATH);
process.stdout.write(JSON.stringify(buildSettings(cfg), null, 2) + "\n");
